### ISSUE TITLE
build failed when eslint was updated from 5.16.0 to 6.0.0.

### ISSUE THREAD

**Issue by hermeslin** [hermeslin/guardian-of-env#23]
PR: #21 

```
Error: Failed to load plugin 'import' declared in '.eslintrc.json » eslint-config-airbnb-base » /home/travis/build/hermeslin/guardian-of-env/node_modules/eslint-config-airbnb-base/rules/imports.js': Cannot find module 'eslint/lib/util/source-code'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/travis/build/hermeslin/guardian-of-env/node_modules/eslint-plugin-import/lib/ExportMap.js:20:19)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command "yarn lint" exited with 1.
```

**Comment by hermeslin** [comment]
https://github.com/airbnb/javascript/issues/2036
airbnb not support eslint v6 yet.
