### ISSUE TITLE
build failed when update babel monorepo

### ISSUE THREAD

**Issue by hermeslin** [hermeslin/guardian-of-env#59]
## PR
#58 

## error message
```
TypeError: Cannot read property 'range' of null
Occurred while linting /Users/hermeslin/Project/node-project/guardian-of-env/src/guardian.js:53
    at SourceCode.getTokenBefore (/Users/hermeslin/Project/node-project/guardian-of-env/node_modules/eslint/lib/source-code/token-store/index.js:298:18)
    at checkSpacingBefore (/Users/hermeslin/Project/node-project/guardian-of-env/node_modules/eslint/lib/rules/template-curly-spacing.js:60:42)
    at TemplateElement (/Users/hermeslin/Project/node-project/guardian-of-env/node_modules/eslint/lib/rules/template-curly-spacing.js:119:17)
    at listeners.(anonymous function).forEach.listener (/Users/hermeslin/Project/node-project/guardian-of-env/node_modules/eslint/lib/linter/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/hermeslin/Project/node-project/guardian-of-env/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/hermeslin/Project/node-project/guardian-of-env/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (/Users/hermeslin/Project/node-project/guardian-of-env/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (/Users/hermeslin/Project/node-project/guardian-of-env/node_modules/eslint/lib/linter/node-event-generator.js:297:14)
    at CodePathAnalyzer.enterNode (/Users/hermeslin/Project/node-project/guardian-of-env/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:634:23)
```

**Comment by hermeslin** [comment]
目前看到的解法是砍掉 yarn.lock 再重新產生一次新的 yarn.lock
或是可以使用 https://github.com/babel/babel-eslint/issues/681#issuecomment-516893539 的解法
